#!/bin/bash
# Exit if any subcommand fails
set -e
set -o pipefail

source script/helpers/text_helpers
source script/helpers/function_helpers

printf "\n▸ Stopping and removing containers, networks, and volumes\n"
compose_command down -v | indent

printf "\n✔ All done.\n"