#!/bin/bash
# Exit if any subcommand fails
set -e
set -o pipefail

source script/helpers/text_helpers
source script/helpers/function_helpers

printf "\n▸ Initializing database\n"
compose_command run --rm PROJECT_NAME /home/lucky/app/script/docker/update_db -s

printf "\n▸ Bringing containers up\n"
compose_command up | indent
